name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Building Project
        run: npm run build

      - name: Testing
        run: npm test
        env:
          SECRET: ${{ secrets.SECRET }}
